name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-latest-commit:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build solution 1
        run: pwd

      - name: Build solution 2
        run: pwd
        working-directory: ${{ github.workspace }}
        
      - run: build.solution.cmd
