name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-latest-commit:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S ./ -B ./out -G "Visual Studio 17 2022" -A Win32
