name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-latest-commit:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build solution 1
        run: dir
        working-directory: ${{ github.workspace }}

      - name: Build solution
        run: build.solution.cmd 
        working-directory: ${{ github.workspace }}
